default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DATABASE_PORT") { 5432 } %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") { "bichoblog_development" } %>

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_TEST_NAME") { "bichoblog_test" } %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
